{% set version = "2.17.0.20240310" %}

package:
  name: types-pygments
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/t/types-pygments/types-Pygments-{{ version }}.tar.gz
    sha256: b1d97e905ce36343c7283b0319182ae6d4f967188f361f45502a18ae43e03e1f
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - types-docutils
    - types-setuptools

test:
  commands:
    - pip check
    - test -f $SP_DIR/pygments-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\pygments-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Pygments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mypy
