{% set version = "2.19.0.20250219" %}

package:
  name: types-pygments
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-pygments/types_pygments-{{ version }}.tar.gz
    sha256: a4a279338c96f3d4f2eb2c4d7c6c5593c88108b185bb5c664f943f781170cd14
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-docutils
    - types-setuptools

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/pygments-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\pygments-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Pygments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mypy
